- name : hostname fix
  hostname : name="chelsea"
  tags: host

- name: users exist
  become : yes
  user: name={{item.name}} state=present password={{item.password}} groups={{item.groups}}
  with_items: '{{users}}'
  tags: users

- name: ~/.ssh for users exsit
  become : yes
  file: path="/home/{{item.name}}/.ssh" state=directory owner={{item.name}} group={{item.name}} mode=0700
  with_items: '{{users}}'
  tags: users

- name: authorized keys is deployed
  become : yes
  copy: src="authorized_keys_for_{{item.name}}" dest="/home/{{item.name}}/.ssh/authorized_keys" owner={{item.name}} group={{item.name}} mode=0600
  with_items: '{{users}}'
  tags: users

- name: sudo configured
  copy: src="sudoers" dest="/etc/sudoers" owner=root group=root mode=0440

- name: sshd is configured
  notify:
    - restart sshd
  copy: src="sshd_config" dest="/etc/ssh/sshd_config" owner=root group=root mode=0600
  tags: sshd

- name: sshd is enabled and started
  service: name=sshd state=running enabled=yes
  tags: sshd

- name: vhost documentroot dir make
  file: path=/var/www/oscillo/{{item}} state=directory owner=apache group=apache mode=0755
  with_items:
  - ['dev']
  - ['_shared']
  - ['prd']
  - ['stg']
  - ['sid']
  tags: oscillo

- name: clone sid
  git: repo=git@github.com:interestic/sid.git dest=/var/www/oscillo/sid version=master accept_hostkey=no key_file=/home/nancy/.ssh/id_rsa force=yes
  tags: oscillo

- name: setup sid [composer insatll]
  shell:  /usr/local/bin/composer install
  args:
    chdir: /var/www/oscillo/sid
  tags: oscillo

- name: setup sid [composer update]

  shell:  /usr/local/bin/composer update
  args:
    chdir: /var/www/oscillo/sid
  tags: oscillo

- name: create .env to sid
  template:
      src: "sid.env"
      dest: /var/www/oscillo/sid/.env
      owner: sid
      group: sid
      mode: 0644
  tags: oscillo

- name: permission change sid directory
  file: path=/var/www/oscillo/sid state=directory owner=apache group=apache mode=0755 recurse=yes
  tags: oscillo