---
rbenv:
  build_requires:
    spec: [autoconf, gdbm-devel, libffi-devel, libyaml-devel, ncurses-devel, openssl-devel, readline-devel]
    others:
      - bzip2
      - gcc
      - git
      - make
      - perl-Digest-SHA
  install_dir: /usr/local/src/rbenv/
  ruby:
    make_opts: ""
    install_versions: 2.2.4
    global: 2.2.4
    local:
      2.2.4: /srv/
  gem:
    bundler:
      version: 1.7.2