---
- name: build requires (ruby spec)
  yum: name={{ item }} state=present
  with_items: '{{rbenv.build_requires.spec}}'
  tags: rbenv

- name: build requires (compiler, and more)
  yum: name={{ item }} state=present
  with_items: '{{rbenv.build_requires.others}}'
  tags: rbenv

- name: clone this project
  git: >
        repo=https://github.com/rbenv/rbenv.git
        dest={{ rbenv.install_dir }} update=no
  tags: rbenv

- name: clone this project (build environment)
  git: >
        repo=https://github.com/rbenv/ruby-build.git
        dest={{ rbenv.install_dir }}plugins/ruby-build/ update=no
  tags: rbenv

- name: generate setup script ==> /etc/profile.d/rbenv_setup.sh
  template: src=bash/rbenv_setup.sh dest=/etc/profile.d/
  tags: rbenv

- name: build ruby ({{ rbenv.ruby.install_versions }})
  shell: >
          $SHELL --login -c 'rbenv versions | \grep {{ item }}
          || {{ rbenv.ruby.make_opts }} rbenv install {{ item }}'
  with_items: '{{rbenv.ruby.install_versions}}'
  tags: rbenv

- name: set global environment ({{ rbenv.ruby.global }})
  shell: $SHELL --login -c 'rbenv global {{ rbenv.ruby.global }}'
  tags: rbenv

- name: set local environment
  shell: >
          $SHELL --login -c 'rbenv local {{ item.key }}'
          chdir={{ item.value }}
  with_dict: "{{ rbenv.ruby.local }}"
  tags: rbenv

- name: install gem * package (parameter > state)
  gem: >
        name={{ item.key }} state={{ item.value.version }}
        executable={{ rbenv.install_dir }}shims/gem user_install=no
  when: item.value.version in ["present", "absent", "latest"]
  with_dict: "{{ rbenv.gem }}"
  tags: rbenv

- name: install gem * package (parameter > version)
  gem: >
        name={{ item.key }} version={{ item.value.version }}
        executable={{ rbenv.install_dir }}shims/gem user_install=no
  with_dict: "{{ rbenv.gem }}"
  ignore_errors: yes
  tags: rbenv